project_id = "blsiiqhijlubzhpmtswc"

[functions.ical-feed]
verify_jwt = false

[functions.ics-sync]
verify_jwt = true

[functions.ics-export]
verify_jwt = true

[functions.ical-sync-fetch]
verify_jwt = true

[functions.sync-smoobu-bookings]
verify_jwt = true

[functions.auto-ical-sync]
verify_jwt = false